export const ADD_BRAND_START = 'ADD_BRAND_START';
export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS';
export const ADD_BRAND_FAIL = 'ADD_BRAND_FAIL';

export const GET_BRAND_START = 'GET_BRAND_START';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const GET_BRAND_FAIL = 'GET_BRAND_FAIL';

export const BRAND_FETCH_EDIT_START = 'BRAND_FETCH_EDIT_START';
export const BRAND_FETCH_EDIT_SUCCESS = 'BRAND_FETCH_EDIT_SUCCESS';
export const BRAND_FETCH_EDIT_FAIL = 'BRAND_FETCH_EDIT_FAIL';

export const BRAND_EDIT_START = 'BRAND_EDIT_START';
export const BRAND_EDIT_SUCCESS = 'BRAND_EDIT_SUCCESS';
export const BRAND_EDIT_FAIL = 'BRAND_EDIT_FAIL';

export const DELETE_BRAND_START = 'DELETE_BRAND_START';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL';


export const BRAND_RESET = 'BRAND_RESET';