export const LEADTYPE_ADD_START = 'LEADTYPE_ADD_START';
export const LEADTYPE_ADD_SUCCESS = 'LEADTYPE_ADD_SUCCESS';
export const LEADTYPE_ADD_FAIL = 'LEADTYPE_ADD_FAIL';

export const LEADTYPE_LIST_START = 'LEADTYPE_LIST_START';
export const LEADTYPE_LIST_SUCCESS = 'LEADTYPE_LIST_SUCCESS';
export const LEADTYPE_LIST_FAIL = 'LEADTYPE_LIST_FAIL';

export const LEADTYPE_FETCH_EDITDATA_START = 'LEADTYPE_FETCH_EDITDATA_START';
export const LEADTYPE_FETCH_EDITDATA_SUCCESS = 'LEADTYPE_FETCH_EDITDATA_SUCCESS';
export const LEADTYPE_FETCH_EDITDATA_FAIL = 'LEADTYPE_FETCH_EDITDATA_FAIL';

export const LEADTYPE_EDIT_START = 'LEADTYPE_EDIT_START';
export const LEADTYPE_EDIT_SUCCESS = 'LEADTYPE_EDIT_SUCCESS';
export const LEADTYPE_EDIT_FAIL = 'LEADTYPE_EDIT_FAIL';

export const LEADTYPE_DELETE_START = 'LEADTYPE_DELETE_START';
export const LEADTYPE_DELETE_SUCCESS = 'LEADTYPE_DELETE_SUCCESS';
export const LEADTYPE_DELETE_FAIL = 'LEADTYPE_DELETE_FAIL';

export const LEADTYPE_FETCH_FROM_CATEGORY_START = 'LEADTYPE_FETCH_FROM_CATEGORY_START';
export const LEADTYPE_FETCH_FROM_CATEGORY_SUCCESS = 'LEADTYPE_FETCH_FROM_CATEGORY_SUCCESS';
export const LEADTYPE_FETCH_FROM_CATEGORY_FAIL = 'LEADTYPE_FETCH_FROM_CATEGORY_FAIL';

export const LEADTYPE_RESET = 'LEADTYPE_RESET';