export const PRODUCT_LIST_START = 'PRODUCT_LIST_START';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_ADD_START = 'PRODUCT_ADD_START';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';

export const PRODUCT_FETCH_EDIT_START = 'PRODUCT_FETCH_EDIT_START';
export const PRODUCT_FETCH_EDIT_SUCCESS = 'PRODUCT_FETCH_EDIT_SUCCESS';
export const PRODUCT_FETCH_EDIT_FAIL = 'PRODUCT_FETCH_EDIT_FAIL';

export const PRODUCT_EDIT_START = 'PRODUCT_EDIT_START';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_FAIL = 'PRODUCT_EDIT_FAIL';

export const PRODUCT_DELETE_START = 'PRODUCT_DELETE_START';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_REMOVE_IMAGE_START = 'PRODUCT_REMOVE_IMAGE_START';
export const PRODUCT_REMOVE_IMAGE_SUCCESS = 'PRODUCT_REMOVE_IMAGE_SUCCESS';
export const PRODUCT_REMOVE_IMAGE_FAIL = 'PRODUCT_REMOVE_IMAGE_FAIL';

export const PRODUCT_IMAGE_REFRESH_START = 'PRODUCT_IMAGE_REFRESH_START';
export const PRODUCT_IMAGE_REFRESH_SUCCESS = 'PRODUCT_IMAGE_REFRESH_SUCCESS';
export const PRODUCT_IMAGE_REFRESH_FAIL = 'PRODUCT_IMAGE_REFRESH_FAIL';

export const PRODUCT_RESET = 'PRODUCT_RESET';
