export const PURCHASE_ENTRY_LIST_START = 'PURCHASE_ENTRY_LIST_START';
export const PURCHASE_ENTRY_LIST_SUCCESS = 'PURCHASE_ENTRY_LIST_SUCCESS';
export const PURCHASE_ENTRY_LIST_FAIL = 'PURCHASE_ENTRY_LIST_FAIL';

export const PURCHASE_ENTRY_PRODUCT_LIST_START = 'PURCHASE_ENTRY_PRODUCT_LIST_START';
export const PURCHASE_ENTRY_PRODUCT_LIST_SUCCESS = 'PURCHASE_ENTRY_PRODUCT_LIST_SUCCESS';
export const PURCHASE_ENTRY_PRODUCT_LIST_FAIL = 'PURCHASE_ENTRY_PRODUCT_LIST_FAIL';

export const PURCHASE_ENTRY_ADD_START = 'PURCHASE_ENTRY_ADD_START';
export const PURCHASE_ENTRY_ADD_SUCCESS = 'PURCHASE_ENTRY_ADD_SUCCESS';
export const PURCHASE_ENTRY_ADD_FAIL = 'PURCHASE_ENTRY_ADD_FAIL';

export const PURCHASE_ENTRY_FETCH_EDIT_START = 'PURCHASE_ENTRY_FETCH_EDIT_START';
export const PURCHASE_ENTRY_FETCH_EDIT_SUCCESS = 'PURCHASE_ENTRY_FETCH_EDIT_SUCCESS';
export const PURCHASE_ENTRY_FETCH_EDIT_FAIL = 'PURCHASE_ENTRY_FETCH_EDIT_FAIL';

export const PURCHASE_ENTRY_EDIT_START = 'PURCHASE_ENTRY_EDIT_START';
export const PURCHASE_ENTRY_EDIT_SUCCESS = 'PURCHASE_ENTRY_EDIT_SUCCESS';
export const PURCHASE_ENTRY_EDIT_FAIL = 'PURCHASE_ENTRY_EDIT_FAIL';

export const PURCHASE_ENTRY_DELETE_START = 'PURCHASE_ENTRY_DELETE_START';
export const PURCHASE_ENTRY_DELETE_SUCCESS = 'PURCHASE_ENTRY_DELETE_SUCCESS';
export const PURCHASE_ENTRY_DELETE_FAIL = 'PURCHASE_ENTRY_DELETE_FAIL';

export const PURCHASE_ENTRY_PRICE_FETCH_START = 'PURCHASE_ENTRY_PRICE_FETCH_START';
export const PURCHASE_ENTRY_PRICE_FETCH_SUCCESS = 'PURCHASE_ENTRY_PRICE_FETCH_SUCCESS';
export const PURCHASE_ENTRY_PRICE_FETCH_FAIL = 'PURCHASE_ENTRY_PRICE_FETCH_FAIL';

export const PURCHASE_ENTRY_CHANGE_FINAL_STATUS_START = 'PURCHASE_ENTRY_CHANGE_FINAL_STATUS_START';
export const PURCHASE_ENTRY_CHANGE_FINAL_STATUS_SUCCESS = 'PURCHASE_ENTRY_CHANGE_FINAL_STATUS_SUCCESS';
export const PURCHASE_ENTRY_CHANGE_FINAL_STATUS_FAIL = 'PURCHASE_ENTRY_CHANGE_FINAL_STATUS_FAIL';

export const PURCHASE_ENTRY_MASTER_LIST_FETCH_START = 'PURCHASE_ENTRY_MASTER_LIST_FETCH_START';
export const PURCHASE_ENTRY_MASTER_LIST_FETCH_SUCCESS = 'PURCHASE_ENTRY_MASTER_LIST_FETCH_SUCCESS';
export const PURCHASE_ENTRY_MASTER_LIST_FETCH_FAIL = 'PURCHASE_ENTRY_MASTER_LIST_FETCH_FAIL';


export const PURCHASE_ENTRY_RESET = 'PURCHASE_ENTRY_RESET';
