export const QUOTATION_LIST_START = 'QUOTATION_LIST_START';
export const QUOTATION_LIST_SUCCESS = 'QUOTATION_LIST_SUCCESS';
export const QUOTATION_LIST_FAIL = 'QUOTATION_LIST_FAIL';

export const QUOTATION_ADD_START = 'QUOTATION_ADD_START';
export const QUOTATION_ADD_SUCCESS = 'QUOTATION_ADD_SUCCESS';
export const QUOTATION_ADD_FAIL = 'QUOTATION_ADD_FAIL';

export const QUOTATION_FETCH_EDIT_START = 'QUOTATION_FETCH_EDIT_START';
export const QUOTATION_FETCH_EDIT_SUCCESS = 'QUOTATION_FETCH_EDIT_SUCCESS';
export const QUOTATION_FETCH_EDIT_FAIL = 'QUOTATION_FETCH_EDIT_FAIL';

export const QUOTATION_EDIT_START = 'QUOTATION_EDIT_START';
export const QUOTATION_EDIT_SUCCESS = 'QUOTATION_EDIT_SUCCESS';
export const QUOTATION_EDIT_FAIL = 'QUOTATION_EDIT_FAIL';

export const QUOTATION_DELETE_START = 'QUOTATION_DELETE_START';
export const QUOTATION_DELETE_SUCCESS = 'QUOTATION_DELETE_SUCCESS';
export const QUOTATION_DELETE_FAIL = 'QUOTATION_DELETE_FAIL';

export const GET_USER_DETAILS_FROM_MOBILE_START = 'GET_USER_DETAILS_FROM_MOBILE_START';
export const GET_USER_DETAILS_FROM_MOBILE_SUCCESS = 'GET_USER_DETAILS_FROM_MOBILE_SUCCESS';
export const GET_USER_DETAILS_FROM_MOBILE_FAIL = 'GET_USER_DETAILS_FROM_MOBILE_FAIL';

export const QUOTATION_FETCH_FROM_CATEGORY_START = 'QUOTATION_FETCH_FROM_CATEGORY_START';
export const QUOTATION_FETCH_FROM_CATEGORY_SUCCESS = 'QUOTATION_FETCH_FROM_CATEGORY_SUCCESS';
export const QUOTATION_FETCH_FROM_CATEGORY_FAIL = 'QUOTATION_FETCH_FROM_CATEGORY_FAIL';

export const SEARCH_PRODUCT_START = 'SEARCH_PRODUCT_START';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAIL = 'SEARCH_PRODUCT_FAIL';

export const GET_INSIDE_PACKING_START = 'GET_INSIDE_PACKING_START';
export const GET_INSIDE_PACKING_SUCCESS = 'GET_INSIDE_PACKING_SUCCESS';
export const GET_INSIDE_PACKING_FAIL = 'GET_INSIDE_PACKING_FAIL';

export const QUOTATION_RESET = 'QUOTATION_RESET';
