export const RACK_LIST_START = 'RACK_LIST_START';
export const RACK_LIST_SUCCESS = 'RACK_LIST_SUCCESS';
export const RACK_LIST_FAIL = 'RACK_LIST_FAIL';

export const RACK_ADD_START = 'RACK_ADD_START';
export const RACK_ADD_SUCCESS = 'RACK_ADD_SUCCESS';
export const RACK_ADD_FAIL = 'RACK_ADD_FAIL';

export const RACK_FETCH_EDIT_START = 'RACK_FETCH_EDIT_START';
export const RACK_FETCH_EDIT_SUCCESS = 'RACK_FETCH_EDIT_SUCCESS';
export const RACK_FETCH_EDIT_FAIL = 'RACK_FETCH_EDIT_FAIL';

export const RACK_EDIT_START = 'RACK_EDIT_START';
export const RACK_EDIT_SUCCESS = 'RACK_EDIT_SUCCESS';
export const RACK_EDIT_FAIL = 'RACK_EDIT_FAIL';

export const RACK_DELETE_START = 'RACK_DELETE_START';
export const RACK_DELETE_SUCCESS = 'RACK_DELETE_SUCCESS';
export const RACK_DELETE_FAIL = 'RACK_DELETE_FAIL';

export const RACK_RESET = 'RACK_RESET';
