export const SERIES_LIST_START = 'SERIES_LIST_START';
export const SERIES_LIST_SUCCESS = 'SERIES_LIST_SUCCESS';
export const SERIES_LIST_FAIL = 'SERIES_LIST_FAIL';

export const SERIES_ADD_START = 'SERIES_ADD_START';
export const SERIES_ADD_SUCCESS = 'SERIES_ADD_SUCCESS';
export const SERIES_ADD_FAIL = 'SERIES_ADD_FAIL';

export const SERIES_FETCH_EDIT_START = 'SERIES_FETCH_EDIT_START';
export const SERIES_FETCH_EDIT_SUCCESS = 'SERIES_FETCH_EDIT_SUCCESS';
export const SERIES_FETCH_EDIT_FAIL = 'SERIES_FETCH_EDIT_FAIL';

export const SERIES_EDIT_START = 'SERIES_EDIT_START';
export const SERIES_EDIT_SUCCESS = 'SERIES_EDIT_SUCCESS';
export const SERIES_EDIT_FAIL = 'SERIES_EDIT_FAIL';

export const SERIES_DELETE_START = 'SERIES_DELETE_START';
export const SERIES_DELETE_SUCCESS = 'SERIES_DELETE_SUCCESS';
export const SERIES_DELETE_FAIL = 'SERIES_DELETE_FAIL';

export const GET_SUBCAT_FROM_CAT_START = 'GET_SUBCAT_FROM_CAT_START';
export const GET_SUBCAT_FROM_CAT_SUCCESS = 'GET_SUBCAT_FROM_CAT_SUCCESS';
export const GET_SUBCAT_FROM_CAT_FAIL = 'GET_SUBCAT_FROM_CAT_FAIL';

export const SERIES_FETCH_FROM_CATEGORY_START = 'SERIES_FETCH_FROM_CATEGORY_START';
export const SERIES_FETCH_FROM_CATEGORY_SUCCESS = 'SERIES_FETCH_FROM_CATEGORY_SUCCESS';
export const SERIES_FETCH_FROM_CATEGORY_FAIL = 'SERIES_FETCH_FROM_CATEGORY_FAIL';

export const SERIES_RESET = 'SERIES_RESET';
