export const SIZEPITCH_ADD_START = 'SIZEPITCH_ADD_START';
export const SIZEPITCH_ADD_SUCCESS = 'SIZEPITCH_ADD_SUCCESS';
export const SIZEPITCH_ADD_FAIL = 'SIZEPITCH_ADD_FAIL';

export const SIZEPITCH_LIST_START = 'SIZEPITCH_LIST_START';
export const SIZEPITCH_LIST_SUCCESS = 'SIZEPITCH_LIST_SUCCESS';
export const SIZEPITCH_LIST_FAIL = 'SIZEPITCH_LIST_FAIL';

export const SIZEPITCH_FETCH_EDITDATA_START = 'SIZEPITCH_FETCH_EDITDATA_START';
export const SIZEPITCH_FETCH_EDITDATA_SUCCESS = 'SIZEPITCH_FETCH_EDITDATA_SUCCESS';
export const SIZEPITCH_FETCH_EDITDATA_FAIL = 'SIZEPITCH_FETCH_EDITDATA_FAIL';

export const SIZEPITCH_EDIT_START = 'SIZEPITCH_EDIT_START';
export const SIZEPITCH_EDIT_SUCCESS = 'SIZEPITCH_EDIT_SUCCESS';
export const SIZEPITCH_EDIT_FAIL = 'SIZEPITCH_EDIT_FAIL';

export const SIZEPITCH_DELETE_START = 'SIZEPITCH_DELETE_START';
export const SIZEPITCH_DELETE_SUCCESS = 'SIZEPITCH_DELETE_SUCCESS';
export const SIZEPITCH_DELETE_FAIL = 'SIZEPITCH_DELETE_FAIL';

export const SIZEPITCH_FETCH_FROM_CATEGORY_START = 'SIZEPITCH_FETCH_FROM_CATEGORY_START';
export const SIZEPITCH_FETCH_FROM_CATEGORY_SUCCESS = 'SIZEPITCH_FETCH_FROM_CATEGORY_SUCCESS';
export const SIZEPITCH_FETCH_FROM_CATEGORY_FAIL = 'SIZEPITCH_FETCH_FROM_CATEGORY_FAIL';

export const SIZEPITCH_RESET = 'SIZEPITCH_RESET';