export const VALUE_LIST_START = 'VALUE_LIST_START';
export const VALUE_LIST_SUCCESS = 'VALUE_LIST_SUCCESS';
export const VALUE_LIST_FAIL = 'VALUE_LIST_FAIL';

export const VALUE_ADD_START = 'VALUE_ADD_START';
export const VALUE_ADD_SUCCESS = 'VALUE_ADD_SUCCESS';
export const VALUE_ADD_FAIL = 'VALUE_ADD_FAIL';

export const VALUE_FETCH_EDIT_START = 'VALUE_FETCH_EDIT_START';
export const VALUE_FETCH_EDIT_SUCCESS = 'VALUE_FETCH_EDIT_SUCCESS';
export const VALUE_FETCH_EDIT_FAIL = 'VALUE_FETCH_EDIT_FAIL';

export const VALUE_EDIT_START = 'VALUE_EDIT_START';
export const VALUE_EDIT_SUCCESS = 'VALUE_EDIT_SUCCESS';
export const VALUE_EDIT_FAIL = 'VALUE_EDIT_FAIL';

export const VALUE_DELETE_START = 'VALUE_DELETE_START';
export const VALUE_DELETE_SUCCESS = 'VALUE_DELETE_SUCCESS';
export const VALUE_DELETE_FAIL = 'VALUE_DELETE_FAIL';

export const VALUE_RESET = 'VALUE_RESET';
